name: first work flow 

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hi:

    runs-on: ubuntu-latest

    steps:
      - name: say hi
        run: echo "hi world"

  hello: 

    runs-on: ubuntu-latest
    needs: hi
    
    steps:
      - name: say hello
        run: echo "Hello worlds"
        
  bye: 

    runs-on: ubuntu-latest
    needs: hello

    steps:
      - name: bye worlds
        run: echo "bye worlds"
